#!/usr/bin/env python3
"""Regenerate tokens/tokens.css from tokens/tokens.json. Run from the repo root."""
import json
from pathlib import Path

t = json.loads(Path("tokens/tokens.json").read_text())


def block(theme, indent="  "):
    rows = [f"{indent}--{x['name']}: {x['value'][theme]};" for x in t["color"]["tokens"]]
    rows += [f"{indent}--{x['name']}: {x['value'] if isinstance(x['value'], str) else x['value'][theme]};" for x in t["shadow"]["tokens"]]
    return "\n".join(rows)


static = "\n".join(
    [f"  --{x['name']}: {x['value']};" for fam in ("spacing", "radius") for x in t[fam]["tokens"]]
    + [f"  --font-{k}: {v};" for k, v in t["type"]["families"].items()]
)

css = f"""/* Bytes & Coffee tokens. Generated by scripts/build_tokens.py from tokens.json; edit that, not this.
   Espresso (dark) is the primary theme. Light applies with data-theme="light",
   or when there is no data-theme and the viewer prefers light. */
:root {{
{block('dark')}
{static}
  color-scheme: dark;
}}
@media (prefers-color-scheme: light) {{
  :root:not([data-theme="dark"]) {{
{block('light', '    ')}
    color-scheme: light;
  }}
}}
:root[data-theme="light"] {{
{block('light')}
  color-scheme: light;
}}
:root[data-theme="dark"] {{
{block('dark')}
  color-scheme: dark;
}}
"""
for group in t["type"]["groups"]:
    for s in group["styles"]:
        fam = s.get("family", group["family"])
        props = [f"font-family: var(--font-{fam})", f"font-size: {s['fontSize']}", f"line-height: {s['lineHeight']}", f"font-weight: {s['fontWeight']}"]
        if "letterSpacing" in s:
            props.append(f"letter-spacing: {s['letterSpacing']}")
        if s.get("fontStyle") == "italic":
            props += ["font-style: italic", 'font-variation-settings: "WONK" 0, "SOFT" 0']
        if s["name"] == "kicker":
            props.append("text-transform: uppercase")
        css += f".{s['name']} {{ {'; '.join(props)}; }}\n"

Path("tokens/tokens.css").write_text(css)
print("wrote tokens/tokens.css")
